server:
  address: 127.0.0.1
  sessionTimeout: 30

spring:
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop

  datasource:
    initialize: true
    continueOnError: false
    platform: mysql
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: root