server:
  address: 0.0.0.0
  sessionTimeout: 30

spring:
  jpa:
    show-sql: false
    generate-ddl: true
    hibernate:
      ddl-auto: update
      show-sql: false

  datasource:
    initialize: false
    continueOnError: true

app:
  name: HotSpring
  redis:
    host: docker_host
    port: 6379